export const TOURS_LIST_REQUEST = "TOURS_LIST_REQUEST";
export const TOURS_LIST_SUCCESS = "TOURS_LIST_SUCCESS";
export const TOURS_LIST_FAILURE = "TOURS_LIST_FAILURE";

export const FETCH_ONE_TOUR_REQUEST = "FETCH_ONE_TOUR_REQUEST";
export const FETCH_ONE_TOUR_SUCCESS = "FETCH_ONE_TOUR_SUCCESS";
export const FETCH_ONE_TOUR_FAILURE = "FETCH_ONE_TOUR_FAILURE";

export const CREATE_OR_UPDATE_TOUR_REQUEST = "CREATE_OR_UPDATE_TOUR_REQUEST";
export const CREATE_OR_UPDATE_TOUR_SUCCESS = "CREATE_OR_UPDATE_TOUR_SUCCESS";
export const CREATE_OR_UPDATE_TOUR_FAILURE = "CREATE_OR_UPDATE_TOUR_FAILURE";

export const ADMIN_DELETE_TOUR_REQUEST = "ADMIN_DELETE_TOUR_REQUEST";
export const ADMIN_DELETE_TOUR_SUCCESS = "ADMIN_DELETE_TOUR_SUCCESS";
export const ADMIN_DELETE_TOUR_FAILURE = "ADMIN_DELETE_TOUR_FAILURE";

export const TOURS_LIST_REQUEST_BY_TOUR_ORGANIZER = "TOURS_LIST_REQUEST_BY_TOUR_ORGANIZER";
export const TOURS_LIST_SUCCESS_BY_TOUR_ORGANIZER = "TOURS_LIST_SUCCESS_BY_TOUR_ORGANIZER";
export const TOURS_LIST_FAILURE_BY_TOUR_ORGANIZER = "TOURS_LIST_FAILURE_BY_TOUR_ORGANIZER";

export const TOUR_ORGANIZER_DELETE_TOUR_REQUEST = "TOUR_ORGANIZER_DELETE_TOUR_REQUEST";
export const TOUR_ORGANIZER_DELETE_TOUR_SUCCESS = "TOUR_ORGANIZER_DELETE_TOUR_SUCCESS";
export const TOUR_ORGANIZER_DELETE_TOUR_FAILURE = "TOUR_ORGANIZER_DELETE_TOUR_FAILURE";

export const ADD_HIKER_TO_TOUR_REQUEST = "ADD_HIKER_TO_TOUR_REQUEST";
export const ADD_HIKER_TO_TOUR_SUCCESS = "ADD_HIKER_TO_TOUR_SUCCESS";
export const ADD_HIKER_TO_TOUR_FAILURE = "ADD_HIKER_TO_TOUR_FAILURE";

export const SHOW_TOURS_OF_HIKER_REQUEST = "SHOW_TOURS_OF_HIKER_REQUEST";
export const SHOW_TOURS_OF_HIKER_SUCCESS = "SHOW_TOURS_OF_HIKER_SUCCESS";
export const SHOW_TOURS_OF_HIKER_FAILURE = "SHOW_TOURS_OF_HIKER_FAILURE";
