export const REGISTER_TOUR_ORGANIZER_REQUEST = "REGISTER_TOUR_ORGANIZER_REQUEST";
export const REGISTER_TOUR_ORGANIZER_SUCCESS= "REGISTER_TOUR_ORGANIZER_SUCCESS";
export const REGISTER_TOUR_ORGANIZER_FAILURE= "REGISTER_TOUR_ORGANIZER_FAILURE";

export const SIGNIN_TOUR_ORGANIZER_REQUEST = "SIGNIN_TOUR_ORGANIZER_REQUEST";
export const SIGNIN_TOUR_ORGANIZER_SUCCESS= "SIGNIN_TOUR_ORGANIZER_SUCCESS";
export const SIGNIN_TOUR_ORGANIZER_FAILURE= "SIGNIN_TOUR_ORGANIZER_FAILURE";

export const LIST_TOUR_ORGANIZERS_REQUEST = "LIST_TOUR_ORGANIZERS_REQUEST";
export const LIST_TOUR_ORGANIZERS_SUCCESS = "LIST_TOUR_ORGANIZERS_SUCCESS";
export const LIST_TOUR_ORGANIZERS_FAILURE = "LIST_TOUR_ORGANIZERS_FAILURE";

export const LIST_TOUR_ORGANIZERS_AUTH_REQUEST = "LIST_TOUR_ORGANIZERS_REQUEST";
export const LIST_TOUR_ORGANIZERS_AUTH_SUCCESS = "LIST_TOUR_ORGANIZERS_SUCCESS";
export const LIST_TOUR_ORGANIZERS_AUTH_FAILURE = "LIST_TOUR_ORGANIZERS_FAILURE";


export const SIGNOUT_TOUR_ORGANIZER= "SIGNOUT_TOUR_ORGANIZER";

export const DELETE_TOUR_ORGANIZER_REQUEST = "DELETE_TOUR_ORGANIZER_REQUEST";
export const DELETE_TOUR_ORGANIZER_SUCCESS = "DELETE_TOUR_ORGANIZER_SUCCESS";
export const DELETE_TOUR_ORGANIZER_FAILURE = "DELETE_TOUR_ORGANIZER_FAILURE";

export const GET_SINGLE_TOUR_ORGANIZER_REQUEST = "GET_SINGLE_TOUR_ORGANIZER_REQUEST";
export const GET_SINGLE_TOUR_ORGANIZER_SUCCESS = "GET_SINGLE_TOUR_ORGANIZER_SUCCESS";
export const GET_SINGLE_TOUR_ORGANIZER_FAILURE = "GET_SINGLE_TOUR_ORGANIZER_FAILURE";

export const GET_SINGLE_TOUR_ORGANIZER_REQUEST_AUTH = "GET_SINGLE_TOUR_ORGANIZER_REQUEST_AUTH";
export const GET_SINGLE_TOUR_ORGANIZER_SUCCESS_AUTH = "GET_SINGLE_TOUR_ORGANIZER_SUCCESS_AUTH";
export const GET_SINGLE_TOUR_ORGANIZER_FAILURE_AUTH = "GET_SINGLE_TOUR_ORGANIZER_FAILURE_AUTH";

export const UPDATE_TOUR_ORGANIZER_REQUEST = "UPDATE_TOUR_ORGANIZER_REQUEST";
export const UPDATE_TOUR_ORGANIZER_SUCCESS = "UPDATE_TOUR_ORGANIZER_SUCCESS";
export const UPDATE_TOUR_ORGANIZER_FAILURE = "UPDATE_TOUR_ORGANIZER_FAILURE";

export const DISPLAY_TOURS_OF_TOUR_ORGANIZER_REQUEST =  "DISPLAY_TOURS_OF_TOUR_ORGANIZER_REQUEST";
export const DISPLAY_TOURS_OF_TOUR_ORGANIZER_FAILURE =  "DISPLAY_TOURS_OF_TOUR_ORGANIZER_FAILURE";
export const DISPLAY_TOURS_OF_TOUR_ORGANIZER_SUCCESS =  "DISPLAY_TOURS_OF_TOUR_ORGANIZER_SUCCESS";